import{a as B,S as m,i as I}from"./assets/vendor-b0d10f48.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const P="44324490-53902a9aa3f8bdbab535f7eec",x="https://pixabay.com/api/";async function p(t,o=1,c=15){const s=`${x}?key=${P}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${c}`,e=await B.get(s);if(e.status!==200)throw new Error("Failed to fetch images");return e.data}const y=document.querySelector(".gallery");function D(){y.innerHTML=""}function g(t){const o=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:E,comments:S,downloads:q})=>`
    <div class="photo-card">
      <a href="${e}" class="gallery__item">
        <img src="${s}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b> ${a}</p>
        <p class="info-item"><b>Views</b> ${E}</p>
        <p class="info-item"><b>Comments</b> ${S}</p>
        <p class="info-item"><b>Downloads</b> ${q}</p>
      </div>
    </div>
  `).join("");y.insertAdjacentHTML("beforeend",o),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const M=document.querySelector("#search-form"),O=document.querySelector("#search-form input"),_=document.querySelector(".gallery"),f=document.getElementById("load-more"),b=document.getElementById("loader");let l="",n=1;const d=15;let u=0;const L=new m(".gallery a",{captionsData:"alt",captionDelay:250});M.addEventListener("submit",async t=>{if(t.preventDefault(),l=O.value.trim(),l===""){i("Search query cannot be empty");return}n=1,D(),$(),w();try{const o=await p(l,n,d);if(u=o.totalHits,o.hits.length===0){i("Sorry, there are no images matching your search query. Please try again.");return}g(o.hits),L.refresh(),u>d&&v()}catch(o){i(o.message)}finally{h()}});f.addEventListener("click",async()=>{n+=1,$(),w();try{const t=await p(l,n,d);g(t.hits),L.refresh(),n*d>=u?i("We're sorry, but you've reached the end of search results."):v(),H()}catch(t){i(t.message)}finally{h()}});function w(){b.classList.remove("hidden")}function h(){b.classList.add("hidden")}function v(){f.classList.remove("hidden")}function $(){f.classList.add("hidden")}function i(t){h(),I.error({title:"Error",message:t,position:"topRight"})}function H(){const{height:t}=_.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
